#!/bin/sh

# Set initial fzf prefix from command-line argument (eg exact match) or default to an empty string
if [ -n "$1" ]; then
    INITIAL_FZF_PREFIX="'$1"
else
    INITIAL_FZF_PREFIX=""
fi

# Get a list of branches
git for-each-ref  --sort=-committerdate  --format='%(refname)' | \
    sed -e 's:^refs/heads/::' -e 's:^refs/remotes/origin/::' | uniq | \
    fzf --no-mouse --preview 'git log -p {} --color --max-count=10' +s --query "$INITIAL_FZF_PREFIX" | \
    xargs -n1 git checkout
